---
title: "Coverage and enrichment testing"
output: 
  rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{2. Coverage and enrichment testing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r 'knitr-setup', include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  dev = "ragg_png", 
  comment = "#>"
)
```

# Overview


## Setup 

```{r 'setup-multifactor', message = FALSE}
library(MultiFactor)

# Wrangling
library(dplyr)

# Plotting
library(ggplot2)
library(systemfonts)
library(ragg)

# Load demo data
set.seed(2612)
fox <- quickbrownfox()

split_to_letters <- function(x) unlist(
  strsplit( gsub(" ", "", x), split = "" ),
  recursive = TRUE, use.names = FALSE
  )
```

### Example Dataset: The Quick Brown Fox 

```{r 'show-data', message = FALSE}
levels(fox)

as.matrix(fox$letter2word)
```

### Calculate coverage

```{r 'setup-example1', message = FALSE}
input <- split_to_letters("some number of letters")

input
```

```{r 'weave-example1', message = FALSE}
res <- weave_coverage(
    x = fox, .path = letter ~ word, .data = input
)

as.data.frame(res)
```

Now, let's use a second set of letters that we know are in the sentence: 
```{r 'setup-example2', message = FALSE}
input <- split_to_letters("jumps over")

input
```

```{r 'weave-example2', message = FALSE}
res <- weave_coverage(
    x = fox, .path = letter ~ word, .data = input
)

as.data.frame(res)
```
Notice that the column named `complete` marks two words as complete now. 

We can use the `subset` method for `LinkMap` to automatically filter for 
complete cases:
```{r 'weave-subset', message = FALSE}
subset(res)
```
